from pygame import display
# config.py
LARGURA = 1280
ALTURA = 720
ALTURA_BASE = 720
VELOCIDADE_BASE_CENARIO = 0.5
FPS = 60

TELA = display.set_mode((LARGURA, ALTURA))

NAVE_LARGURA = 80
NAVE_ALTURA = 80
VELOCIDADE_NAVE_BASE = 5
VELOCIDADE_TIRO = 10

INTERVALO_SPAWN_INIMIGO = 1500
QUANT_INIMIGOS_INICIO = 20
QUANT_INIMIGOS_MAX = 20

EFEITO_DURACAO = 5000

VELOCIDADE_COLETAVEL = 2.5

MAX_PONTUACAO = 300
COOLDOWN = 100
